<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RollForward>LatestMajor</RollForward>
    <RootNamespace>ProcAnim.Core.DaddyLongLegsSmoke</RootNamespace>
    <AssemblyName>ProcAnim.Core.DaddyLongLegsSmoke</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ProcAnim.Core.csproj" />
  </ItemGroup>
</Project>
